language: node_js
node_js:
  - 7.7
before_script:
  - npm uninstall -g typescript
  - npm install -g typescript@2.1.x
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: "52.0"

